### ISSUE TITLE
Qt5 GUI for safe erasing disks using your library

### ISSUE THREAD

**Issue by nestorac** [linuxdeepin/udisks2-qt5#10]
I work for an NGO, we provide secure erase services to reuse HDDs, they send us many disks (up  to 500), we erase them, fill a form, reuse them. We fill them with just zeroes, filling with random data is too slow.

The problem is that we need to manage ~10 disks at the same time (same computer, they have 6 SATA + 4 PCI SATA), now we use the console, we have set up 12 virtual consoles (Ctr+F1-F12), but it's a bit confusing. Just imagine, we have to use /dev/disk/by-path/[device], because normal drive letters do not correspond to a particular SATA socket (let's say, 'sda' and so).

I want to develop a GUI to safely erase the disks, in a future it will get more complex (recording serial numbers, sending to a local DB, printing labels...), but for now we only need to erase the disks easily.

Personally, I have some experience with Qt5, I have discovered this library, but it lacks documentation. I have tried dde-device-formatter, I wonder if libudisks2-qt5 is able to erase a whole disk.

Well, could you please give me some piece of advice? I need to be able to have the right tools to begin with the development of the app.

**Comment by deepin-CD** [comment]
In your case, libudisks2-qt5 seems like a good choice, which could minitor the hot-plugin of disks and operate the devices.
the only thing you should do is just make an instance of DDiskManager and then setWatchChanges, after that, connect the signals which could tell the changes of the divice.
if you wanna get the object of the device, just call DDiskManager::createBlockDevice etc.
if you're still confusing about how to use this lib, please see how our file-manager did, the simplest reference is the subproject of file-manager which is called dde-dock-plugin.

NOTICE that if you're using disk manager meantime, such as gnome disk and gparted, the signals will reemit when the diskmanager application launched.

**Comment by itsXuSt** [comment]
> In your case, libudisks2-qt5 seems like a good choice, which could minitor the hot-plugin of disks and operate the devices.
> the only thing you should do is just make an instance of DDiskManager and then setWatchChanges, after that, connect the signals which could tell the changes of the divice.
> if you wanna get the object of the device, just call DDiskManager::createBlockDevice etc.
> if you're still confusing about how to use this lib, please see how our file-manager did, the simplest reference is the subproject of file-manager which is called dde-dock-plugin. https://github.com/linuxdeepin/dde-file-manager/tree/uos/dde-dock-plugins/disk-mount
> 
> NOTICE that if you're using disk manager meantime, such as gnome disk and gparted, the signals will reemit when the diskmanager application launched.

**Comment by itsXuSt** [comment]
if you wanna ERASE your disks through this project, i'm not sure if this will satisfy you.

**Comment by nestorac** [comment]
Yes, I want to **erase** them, fill them with zeroes, I'll take a look, thank you!

**Comment by itsXuSt** [comment]
> Yes, I want to **erase** them, fill them with zeroes, I'll take a look, thank you!

libudisks2-qt5 do provide a function named `format`, you could just call the d-bus interface to verify if it is useful.
simply invoke it with d-feet
![image](https://user-images.githubusercontent.com/50353838/110732860-df2e9800-821c-11eb-9d9c-7aa0a8e12b43.png)

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
