### ISSUE TITLE
How to automount drives with this library?

### ISSUE THREAD

**Issue by diracsbracket** [linuxdeepin/udisks2-qt5#11]
Hi.
I am looking for a solution to automount USB drives. Can this be done with this library?

**Comment by BLumia** [comment]
`DDiskManager` provided some useful signals that can be used to implement automount. You can take [this](https://github.com/linuxdeepin/dde-file-manager/blob/6b40ecd3076e21dc11064f86b333f76db205387b/src/dde-dock-plugins/disk-mount/diskcontrolwidget.cpp#L98-L104) as a reference. They are a wrapper of `/org/freedesktop/UDisks2/`, you can also read the udisks manual to learn more about it.

**Comment by diracsbracket** [comment]
Hi Gary,
Thanks! I will have a look and try it!

**Comment by deepin-CD** [comment]
We do this in dde-file-manager/dde-dock-plugins, so you can read the codes of this project.
Just watch the signals and invoke DBlockDevice::mount to achive your needs.

**Comment by diracsbracket** [comment]
Hi Gary,
I managed to integrate the relevant code of DiskControllerWidget +
udisks2-qt + gio-qt in my program,
but for the moment, only device removals are being reported, no device
insertions.

The problem really is my limited understanding of the relation between
udisks2-qt, gio-qt and daemons like
udisks2 and gvfs (and its associated daemons) and it seems that the more I
read about it,
the more confusing it all becomes.

In any case, thanks again for your kind reply!
Paul

**Comment by diracsbracket** [comment]
Hi Gary,
I managed to integrate the relevant code of DiskControllerWidget +
udisks2-qt + gio-qt in my program,
but for the moment, only device removals are being reported, no device
insertions.

The problem really is my limited understanding of the relation between
udisks2-qt, gio-qt and daemons like
udisks2 and gvfs (and its associated daemons) and it seems that the more I
read about it,
the more confusing it becomes. It is not clear at all what does what. I
thought UDisks2 could do it all,
but haven't yet found an example that solely uses UDisks2. They always seem
to rely on GVfs as well,
like, Deepin OS also does.

In any case, thanks again for your kind reply!
Paul

**Comment by BLumia** [comment]
> but for the moment, only device removals are being reported, no device
> insertions.

Both *udisks* and *gio* can fit what you need but you actually just need one of them. Check out the manual of `udisksctl monitor` command **or** `gio monitor` so you can use them for testing/debugging. If that works fine but the library didn't, you may need to provide some details so developers from deepin could help.

> The problem really is my limited understanding of the relation between
> udisks2-qt, gio-qt and daemons like
> udisks2 and gvfs (and its associated daemons) and it seems that the more I
> read about it,

`udisks2-qt` is a Qt wrapper of udisks' d-bus method, `gio-qt` is a Qt wrapper of the library `giomm`. Read the UDisks or GIO manual to learn more, but you just need to pick one of them :)

> but haven't yet found an example that solely uses UDisks2. They always seem
> to rely on GVfs as well,

The reason why deepin uses both GIO and UDisks is, they use GIO to handle network devices/mount points. If you don't need to do that, use UDisks only will be enough. KDE uses their KIO so KDE stuff doesn't actually rely on GVFS.

Maybe people from deepin could offer more help :)

**Comment by diracsbracket** [comment]
Thanks @BLumia
I have managed to get it working using udisks2 only, well almost.
When inserting new thumb drives, it is detected and automounted, and sometimes, that persists between boots (if I don't unplug it). But at some point, after boot, the already plugged in thumb drives won't have automounted, and I need to manually unplug then replug the drives...  I still need to find the cause of this and its solution.
But in any case, looking at the deepin example helped me a lot.
Cheers!
