### ISSUE TITLE
How compile this project for my ubuntu?

### ISSUE THREAD

**Issue by styapark** [linuxdeepin/udisks2-qt5#8]
How compile this project for my ubuntu 19.10?
i need to compile deep file manager. cause i cant install deepin file manager from https://launchpad.net/~leaeasy/+archive/ubuntu/dde

sorry if my language is ugly

**Comment by BLumia** [comment]
Just normal qmake steps, something like:

``` shell
$ cd /path/to/the/source/
$ mkdir build
$ cd build
$ qmake ../
$ make
$ sudo make install
```

btw before you start compile the file manager app (or whatever other DDE apps), make sure you are on the lastest **tag** since you are probably not able to compile it if you are on the HEAD of master branch :)

**Comment by styapark** [comment]
this log when run to make

`...
process translations/dde-file-manager_zh_CN.ts
Updating 'translations/dde-file-manager_zh_CN.qm'...
    Generated 571 translation(s) (571 finished and 0 unfinished)

process translations/dde-file-manager_zh_TW.ts
Updating 'translations/dde-file-manager_zh_TW.qm'...
    Generated 565 translation(s) (565 finished and 0 unfinished)
    Ignored 6 untranslated source text(s)
Project ERROR: udisks2-qt5 development package not found
make: *** [Makefile:105: sub-dde-file-manager-lib-make_first] Error 3
`
udisk2-qt5 is not found

**Comment by BLumia** [comment]
Did you compile and install `udisks2-qt5` first?

**Comment by styapark** [comment]
yes, first time for my ubuntu

**Comment by BLumia** [comment]
Did the install process of your `udisks2-qt5` installs a `udisks2-qt5.pc` file to your system(under `/usr/lib/x86_64-linux-gnu/pkgconfig/` or other places which `pkg-config` can find)?

If did, what's the result of `pkg-config --list-all | grep udisks`

**Comment by BLumia** [comment]
Closing since no response for a long period. If you still got any issues while compiling this project, please create a new issue or discussion thread in the [developer-center](https://github.com/linuxdeepin/developer-center) repo. Thanks.
